# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20180409_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.URLField(default='no', max_length=1000),
            preserve_default=False,
        ),
    ]
