# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
