# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='twitter_handler',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
