# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(default=' ', upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
