# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_instructor_head_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
