# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 09:21
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20180404_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='head_shot',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=b'instructorsImage'),
        ),
    ]
